name: Validate JSON Files

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run script (testnet)
      run: |
        source venv/bin/activate
        python scripts/validate_protocol.py --network testnet

    - name: Run script (mainnet)
      run: |
        source venv/bin/activate
        python scripts/validate_protocol.py --network mainnet
